// Route 67 design tokens
window.TOKENS = {
  // themes
  themes: {
    light: {
      bg: '#F7F9F5',
      surface: '#FFFFFF',
      surfaceAlt: '#EEF5EC',
      text: '#0A3A1F',
      textMuted: '#4A6B57',
      textFaint: '#8AA296',
      border: '#D9E6DA',
      primary: '#00B14F',      // grab green
      primaryDark: '#008F3F',
      primaryTint: '#E6F7EC',
      accent: '#FF3D8A',       // meme pink
      mapLand: '#EAF2E4',
      mapRoad: '#FFFFFF',
      mapRoadMajor: '#FFFFFF',
      mapWater: '#C8E1D4',
      mapPark: '#CFE6BC',
      mapBuilding: '#DCE7D4',
      mapLabel: '#6B8574',
      radius: '#00B14F',
    },
    dark: {
      bg: '#0B1410',
      surface: '#121E17',
      surfaceAlt: '#182A20',
      text: '#EAFBEF',
      textMuted: '#9EB7A6',
      textFaint: '#6A8274',
      border: '#223428',
      primary: '#2BDB75',
      primaryDark: '#1FC263',
      primaryTint: '#14321F',
      accent: '#FF4F95',
      mapLand: '#0F1C15',
      mapRoad: '#223428',
      mapRoadMajor: '#2A4230',
      mapWater: '#0A2A22',
      mapPark: '#1A3623',
      mapBuilding: '#18261C',
      mapLabel: '#6F9280',
      radius: '#2BDB75',
    },
    meme: {
      // loud, chaotic but still legible
      bg: '#FFF4E0',
      surface: '#FFFFFF',
      surfaceAlt: '#FFE9BA',
      text: '#10241B',
      textMuted: '#6B4E1F',
      textFaint: '#B08B48',
      border: '#F2D58A',
      primary: '#00B14F',
      primaryDark: '#008F3F',
      primaryTint: '#E6F7EC',
      accent: '#FF3D8A',
      mapLand: '#FFF0D0',
      mapRoad: '#FFFFFF',
      mapRoadMajor: '#FFFFFF',
      mapWater: '#BDE2C9',
      mapPark: '#D6EAB1',
      mapBuilding: '#F2DDA7',
      mapLabel: '#8B6A2E',
      radius: '#FF3D8A',
    },
  },
  rarity: {
    common:    { label: 'Common',    color: '#8AA296', glow: 'rgba(138,162,150,0.35)' },
    rare:      { label: 'Rare',      color: '#2A7FFF', glow: 'rgba(42,127,255,0.45)' },
    legendary: { label: 'Legendary', color: '#FFB020', glow: 'rgba(255,176,32,0.55)' },
  },
  fontDisplay: '"Archivo Black", "Arial Black", system-ui, sans-serif',
  fontBody: 'Inter, ui-sans-serif, system-ui, -apple-system, sans-serif',
};
